name: Update Changelog
on: 
  push:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update changelog
        uses: patrickjahns/chlgr@v1
        with:
          release-version: ${{ steps.version.outputs.next-version }}
      - name: draft release
        uses: release-drafter/release-drafter@master
        with:
          version: ${{ format('{0}', steps.version.outputs.next-version) }}
          tag: ${{ format('{0}', steps.version.outputs.next-version) }}
          name: ${{ format('{0}', steps.version.outputs.next-version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}